# Generated by Django 5.0.3 on 2024-03-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_time', models.CharField(choices=[('1', '8-10'), ('2', '10-12'), ('3', '12-14'), ('4', '14-16'), ('5', '16-18'), ('6', '18-20')], max_length=1)),
                ('reserved_day', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.account')),
            ],
        ),
    ]
