# Generated by Django 5.0.3 on 2024-03-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_time',
            field=models.CharField(choices=[('8-10', '8-10'), ('10-12', '10-12'), ('12-14', '12-14'), ('14-16', '14-16'), ('16-18', '16-18'), ('18-20', '18-20')], max_length=5),
        ),
    ]
